#!/usr/bin/env python
"""Generate the frozen warmup episodes R4 consumes.

Each episode is a completed audit -> repair on a *held-out* item, generated by the auditor itself at
T=0 so it is genuinely that model's own work, then frozen. Two properties this exists to guarantee:

* **The items are held out**, drawn from the `warmup` arm of `allocation.json`. A warmup item that
  was also a clean-arm target would mean the model had already audited *and repaired* the trace it
  is later asked to judge cold.
* **T=0**, because an episode resampled per cell would vary between cells and the 2x2 depends on it
  being byte-identical across all four.

`--from-injection` builds the pool from *faulty* traces instead: 88%/86% of the Qwen models'
ordinary episodes report "correct", which leaves the effect confounded with verdict priming, and
episodes on broken traces invert the verdict while keeping the audit->repair structure. Those traces
come from the `source` arm, also disjoint from the clean targets.
"""

from __future__ import annotations

import argparse
import asyncio
import json
from pathlib import Path

from datasets import load_dataset

from critxer.core import backend
from critxer.core.audit import AUDIT_SCHEMA, AuditItem, build_audit_messages, parse_audit
from critxer.core.backend import parse_endpoint
from critxer.core.paths import artefact
from critxer.core.r4 import (
    NEUTRAL_REQUEST,
    REPAIR_REQUEST,
    injected_candidates,
    natural_candidates,
)

# The filler control's prior exchange: a non-audit task on the same material, so the only thing
# separating it from the 2x2 cells is what the exchange was about.
FILLER_REQUEST = (
    "Restate the following problem in your own words, in about {words} words, without solving it."
)

SPLITS = ("gsm8k", "math", "olympiadbench", "omnimath")
AUDIT_MAX_TOKENS = 512
REPAIR_MAX_TOKENS = 1024




async def episode(http, ep, item: AuditItem, family: str) -> dict | None:
    """One audit -> repair pair at temperature 0, or None if either half is unusable.

    ``problem`` and ``steps`` are stored inline as well as the id: injected items are corrupted
    traces that exist only in the injection set, and one record format for both keeps the consumer
    from having to know which kind it is holding.
    """
    audit_msgs = build_audit_messages(item, "R0", family)
    raws = await backend.sample(http, ep, audit_msgs, n=1, temperature=0.0,
                                max_tokens=AUDIT_MAX_TOKENS, schema=AUDIT_SCHEMA)
    if not raws or raws[0] is None:
        return None
    audit = raws[0].strip()
    parsed = parse_audit(audit, len(item.steps))
    if parsed is None:
        return None

    # The repair request is the same string R4 splices in, so the frozen episode and the live
    # prompt cannot drift apart.
    repair_msgs = [*audit_msgs,
                   {"role": "assistant", "content": audit},
                   {"role": "user", "content": REPAIR_REQUEST}]
    raws = await backend.sample(http, ep, repair_msgs, n=1, temperature=0.0,
                                max_tokens=REPAIR_MAX_TOKENS)
    if not raws or raws[0] is None:
        return None
    return {"item_id": item.item_id, "problem": item.problem, "steps": item.steps,
            "reported_error": parsed.reported_error, "audit": audit, "repair": raws[0].strip()}


async def filler(http, ep, item: AuditItem, target_chars: int) -> dict | None:
    """A non-audit prior exchange, asked to land near ``target_chars``.

    Length is what makes this a control rather than a different manipulation: a filler much shorter
    than the audit+repair it replaces leaves a null ambiguous between "the episode is what matters"
    and "this control was too small to matter".
    """
    # ~5.5 chars per word for this register; the run reports the achieved lengths either way.
    words = max(30, round(target_chars / 5.5))
    request = FILLER_REQUEST.format(words=words) + "\n\n" + item.problem
    raws = await backend.sample(http, ep, [{"role": "user", "content": request}],
                                n=1, temperature=0.0, max_tokens=REPAIR_MAX_TOKENS)
    if not raws or raws[0] is None:
        return None
    return {"item_id": item.item_id, "request": request, "response": raws[0].strip()}


async def neutral(http, ep, item: AuditItem, audit: str, target_chars: int,
                  family: str) -> dict | None:
    """A non-repair continuation of the audit, asked to land near ``target_chars``.

    The continuation the AN cell substitutes for the repair. It must be generated *in the episode's
    own context*, so the only thing separating AN from AS is what the second assistant turn does,
    not how it was produced. Length matters for the same reason as `filler`: a restatement much
    shorter than the repair would leave AS - AN partly a length contrast.
    """
    audit_msgs = build_audit_messages(item, "R0", family)
    words = max(30, round(target_chars / 5.5))
    ask = f"{NEUTRAL_REQUEST} Use about {words} words."
    raws = await backend.sample(
        http, ep,
        [*audit_msgs, {"role": "assistant", "content": audit}, {"role": "user", "content": ask}],
        n=1, temperature=0.0, max_tokens=REPAIR_MAX_TOKENS)
    if not raws or raws[0] is None:
        return None
    return {"item_id": item.item_id, "neutral": raws[0].strip()}


async def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--endpoint", required=True, metavar="LABEL=MODEL@URL")
    ap.add_argument("--family", default="F1")
    ap.add_argument("--concurrency", type=int, default=16)
    ap.add_argument("--allocation", default=str(artefact("allocation.json")))
    ap.add_argument("--out", default="")
    ap.add_argument("--filler", default="",
                    help="also write a length-matched non-audit filler set to this path")
    ap.add_argument("--from-natural", default="",
                    help="build the AX pool from ProcessBench's own labelled-incorrect traces "
                         "instead of injected faults. Removes the injector, so Ministral becomes "
                         "eligible for AX/AXN. Excludes every id in --exclude-arm.")
    ap.add_argument("--exclude-arm", default=str(artefact("incorrect_arm.json")),
                    help="ids that must NOT enter a --from-natural pool: the detection arm's "
                         "targets. A collision means the model repaired a trace it later judges.")
    ap.add_argument("--from-injection", default="",
                    help="build episodes from this injection set's faulty traces instead of the "
                         "warmup arm, so the audit reports an error and the repair is real")
    ap.add_argument("--limit", type=int, default=0,
                    help="cap on candidates drawn from --from-injection (0 = all)")
    ap.add_argument("--require-error", action="store_true", default=False,
                    help="keep only episodes whose audit reported an error")
    ap.add_argument("--pool-size", type=int, default=0,
                    help="cap the KEPT pool after --require-error (0 = no cap). Over-draw with "
                         "--limit, then cap here: the R4 contrasts cluster on the episode and the "
                         "cluster bootstrap is calibrated at ~50 clusters x ~9 targets, so a pool "
                         "of a different size changes the geometry the intervals were checked at. "
                         "Truncation keeps the round-robin source order, so it stays stratified.")
    ap.add_argument("--episodes-in", default="",
                    help="load this frozen episode file instead of generating; REQUIRED when only "
                         "adding --neutral or --filler to an existing pool, because regenerating "
                         "at T=0 is not reproducible on this stack and drifts the pool")
    ap.add_argument("--neutral", default="",
                    help="also write length-matched non-repair continuations here (AN cell)")
    args = ap.parse_args()
    ep = parse_endpoint(args.endpoint)
    out = Path(args.out or artefact(f"warmup_episodes_{ep.label}_{args.family}.json"))
    gate = asyncio.Semaphore(args.concurrency)

    if args.episodes_in:
        # Generating a derived set (neutral continuations, fillers) must never touch the episodes
        # they are matched to. Regenerating them at T=0 drifted 25 of 50 on one model, which
        # silently decoupled derived sets from the cells already measured against the originals.
        blob_in = json.loads(Path(args.episodes_in).read_text())
        if blob_in["auditor"] != ep.label:
            raise SystemExit(f"{args.episodes_in} is {blob_in['auditor']!r}, endpoint {ep.label!r}")
        built = blob_in["episodes"]
        # Pools written before the inline problem/steps fields existed carry only item_id, so fall
        # back to ProcessBench for those -- the same fallback run_r4.episode_pool uses. Injected
        # pools cannot be looked up (corrupted steps exist only in the injection set), but
        # they always carry the fields inline.
        need = {e["item_id"] for e in built if "steps" not in e}
        lookup: dict[str, dict] = {}
        if need:
            for split in SPLITS:
                ds = load_dataset("Qwen/ProcessBench", split=split,
                                  cache_dir=str(artefact("processbench")))
                lookup.update({r["id"]: r for r in ds if r["id"] in need})
            gap = need - lookup.keys()
            if gap:
                raise SystemExit(f"{len(gap)} episode items not in ProcessBench, e.g. "
                                 f"{sorted(gap)[:3]}; cannot rebuild their prompts")
        items = [
            AuditItem(e["item_id"], e["problem"], e["steps"]) if "steps" in e
            else AuditItem(e["item_id"], lookup[e["item_id"]]["problem"],
                           list(lookup[e["item_id"]]["steps"]))
            for e in built
        ]
        print(f"loaded {len(built)} frozen episodes from {args.episodes_in} (not regenerated)"
              + (f"; {len(need)} prompts rebuilt from ProcessBench" if need else ""))
    elif args.from_natural:
        # ProcessBench ships the faults, so there is no injector and no author to attribute them
        # to. What must still hold is disjointness from the detection arm, which draws 929 traces
        # from this same split -- natural_candidates() enforces it from --exclude-arm.
        blob = json.loads(Path(args.from_natural).read_text())
        traces = blob["traces"] if isinstance(blob, dict) else blob
        excl = json.loads(Path(args.exclude_arm).read_text()) if args.exclude_arm else {}
        # Plain ids: ProcessBench's own ids already carry the split, and natural_candidates()
        # compares against them directly. Re-prefixing here would build "gsm8k-gsm8k-212" and the
        # exclusion would silently match nothing -- the pool would then be free to draw the very
        # targets the model is later asked to judge cold.
        used = {str(t["id"]) for t in (excl.get("traces", []) if isinstance(excl, dict) else excl)}
        items = natural_candidates(traces, args.limit or 3 * 50, exclude=used)
        if not items:
            raise SystemExit("--from-natural pool is empty after excluding the detection arm")
        print(f"natural-fault candidates: {len(items)} drawn round-robin across sources, "
              f"{len(used)} detection-arm ids excluded", flush=True)
    elif args.from_injection:
        # The injected pairs come from the `source` arm, which allocation.json holds disjoint from
        # both the clean targets and the warmup arm -- so an episode built here can never be a
        # trace the model is later asked to judge cold. run_r4.py asserts this again anyway.
        pairs = json.loads(Path(args.from_injection).read_text())["pairs"]
        items = injected_candidates(pairs, args.limit or 2 * len(pairs))
        print(f"injected candidates: {len(items)} from {len(pairs)} source traces "
              "(early arm first, then late)")
    else:
        wanted = set(json.loads(Path(args.allocation).read_text())["arms"]["warmup"])
        rows: dict[str, dict] = {}
        for split in SPLITS:
            ds = load_dataset("Qwen/ProcessBench", split=split,
                              cache_dir=str(artefact("processbench")))
            rows.update({r["id"]: r for r in ds if r["id"] in wanted})
        missing = wanted - rows.keys()
        if missing:
            raise RuntimeError(f"{len(missing)} warmup ids not found, e.g. {sorted(missing)[:3]}")
        items = [AuditItem(i, rows[i]["problem"], list(rows[i]["steps"])) for i in sorted(wanted)]
        print(f"warmup items: {len(items)} (held out from the clean arm by allocation.json)")

    if not args.episodes_in:
        async def one(item):
            async with gate:
                return await episode(http, ep, item, args.family)

        async with backend.client() as http:
            built = [e for e in await asyncio.gather(*(one(i) for i in items)) if e]

        print(f"episodes generated: {len(built)} / {len(items)}")
    flagged = sum(1 for e in built if e.get("reported_error"))
    print(f"  of which the audit reported an error: {flagged}")
    if args.require_error:
        # Filtering after generation, not before: whether the model spots a given injected fault
        # is only known once it has audited it, and detection on this set runs 0.35-0.90.
        built = [e for e in built if e["reported_error"]]
        print(f"  --require-error keeps {len(built)}")
    if args.pool_size and len(built) > args.pool_size:
        built = built[:args.pool_size]
        print(f"  --pool-size caps the pool at {len(built)}")
    lens = sorted(len(e["repair"]) for e in built)
    if lens:
        print(f"  repair length chars: min {lens[0]} median {lens[len(lens) // 2]} max {lens[-1]}")

    if args.episodes_in:
        print("skipping episode write: --episodes-in means the pool is frozen input, not output")
    else:
        out.write_text(json.dumps(
            {"auditor": ep.label, "model": ep.model, "family": args.family,
             "temperature": 0.0, "n": len(built), "episodes": built}, indent=1))
        print(f"wrote {out}")

    if args.neutral:
        async with backend.client() as http:
            # Uses the already-resolved `items`, which handles pools that carry only item_id, rather
            # than re-reading fields that older episode files do not have.
            by_id = {e["item_id"]: e for e in built}

            async def one_neutral(item):
                # Keyed on the item id like the filler path below, not zipped positionally.
                # `--require-error` and `--pool-size` both filter `built` after generation, and a
                # positional zip could only fail loudly on the length check, so the two derived
                # sets could not be built in the same invocation as a filtered pool.
                e = by_id.get(item.item_id)
                if e is None:
                    return None
                async with gate:
                    return await neutral(http, ep, item, e["audit"], len(e["repair"]), args.family)
            neutrals = [n for n in await asyncio.gather(
                *(one_neutral(i) for i in items)) if n]
        by_id = {e["item_id"]: e for e in built}
        rep = sorted(len(by_id[n["item_id"]]["repair"]) for n in neutrals)
        neu = sorted(len(n["neutral"]) for n in neutrals)
        print(f"neutral continuations: {len(neutrals)} / {len(built)}")
        print(f"  repair chars: median {rep[len(rep) // 2]}  "
              f"neutral chars: median {neu[len(neu) // 2]}")
        Path(args.neutral).write_text(json.dumps(
            {"auditor": ep.label, "model": ep.model, "family": args.family,
             "temperature": 0.0, "n": len(neutrals), "neutrals": neutrals}, indent=1))
        print(f"wrote {args.neutral}")

    if args.filler:
        by_id = {e["item_id"]: e for e in built}
        async with backend.client() as http:
            async def one_filler(item):
                e = by_id.get(item.item_id)
                if e is None:
                    return None
                async with gate:
                    return await filler(http, ep, item, len(e["audit"]) + len(e["repair"]))
            fillers = [f for f in await asyncio.gather(*(one_filler(i) for i in items)) if f]
        ep_len = sorted(len(by_id[f["item_id"]]["audit"]) + len(by_id[f["item_id"]]["repair"])
                        for f in fillers)
        fl_len = sorted(len(f["response"]) for f in fillers)
        print(f"filler episodes: {len(fillers)} / {len(built)}")
        print(f"  episode chars: median {ep_len[len(ep_len) // 2]}  "
              f"filler chars: median {fl_len[len(fl_len) // 2]}")
        Path(args.filler).write_text(json.dumps(
            {"auditor": ep.label, "model": ep.model, "family": args.family,
             "temperature": 0.0, "n": len(fillers), "fillers": fillers}, indent=1))
        print(f"wrote {args.filler}")


if __name__ == "__main__":
    asyncio.run(main())
