"""The R4 2x2: experienced repair responsibility.

The context carries a completed audit->repair episode on a different (warmup) item before the
target item's audit request. Attributing that episode to another model needs either a relabelled
assistant turn (a *stated* attribution, which Khullar et al. report is null) or a move into a user
turn (which reintroduces their placement confound), so the two factors are crossed:

                    attribution: self      attribution: peer
    assistant turn  AS  natural own        AO  labeled peer, structurally own
    user turn       US  labeled self,      UO  natural peer
                        structurally peer

The off-diagonal cells (AO, US) identify whether an effect rides on **placement** or on **the
label**. Everything but placement and a length-matched label is byte-identical across the four
cells, and the target request is byte-identical to R0's; `tests/test_r4.py` enforces both by
stripping labels and comparing concatenated turns.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass

from critxer.core.audit import AuditItem, build_audit_messages

CELLS = ("AS", "AO", "US", "UO")

# Equal length so a cell cannot differ from another in token count via its label alone.
LABELS = {"self": "[author: self]", "peer": "[author: peer]"}

_PLACEMENT = {"AS": "assistant", "AO": "assistant", "US": "user", "UO": "user"}
_ATTRIBUTION = {"AS": "self", "AO": "peer", "US": "self", "UO": "peer"}

REPAIR_REQUEST = "Now produce the corrected solution."
HANDOFF = (
    "The exchange above is earlier work on a different problem. Audit the following solution."
)


@dataclass(frozen=True)
class FillerEpisode:
    """A prior exchange on a non-audit task, controlling for context per se.

    Length is what makes this a control rather than a different manipulation, so the generator
    matches the filler response to the audit+repair length it stands in for.
    """

    request: str
    response: str


@dataclass(frozen=True)
class WarmupEpisode:
    """A completed audit->repair on a different item, pre-generated once and then frozen.

    Generated by the same model at T=0 so it is genuinely that model's own work, then held fixed
    across the four cells so only placement and attribution vary.
    """

    item: AuditItem
    audit: str
    repair: str


def episode_items(eps: list[dict], lookup: dict[str, AuditItem]) -> list[AuditItem]:
    """The audited item behind each episode, preferring the fields the pool carries inline.

    Fault pools carry their steps inline because those steps exist nowhere else: the trace
    ProcessBench holds under the same id is the *clean* one. `lookup` arrives already resolved, so
    this module stays free of dataset I/O.
    """
    out = []
    for e in eps:
        if "steps" in e:
            out.append(AuditItem(e["item_id"], e["problem"], list(e["steps"])))
            continue
        item = lookup.get(e["item_id"])
        if item is None:
            raise SystemExit(
                f"episode {e['item_id']!r} carries no inline steps and is not in the lookup; "
                "a pool whose steps exist only in the pool cannot be rebuilt from ProcessBench"
            )
        out.append(item)
    return out


def episode_fingerprint(episodes: list[WarmupEpisode]) -> str:
    """A content hash of a frozen episode pool, recorded in every cell built from it.

    T=0 is not reproducible under vLLM continuous batching: regenerating the pools drifted 25 of 50
    episodes on one model, which silently gives two cells of the same condition different episodes.
    The analysis refuses to form a contrast across two values of this hash.
    """
    h = hashlib.sha256()
    for e in episodes:
        h.update(e.item.item_id.encode())
        h.update(e.audit.encode())
        h.update(e.repair.encode())
    return h.hexdigest()[:16]


INCORRECT_VERDICT_CELLS = ("AX", "AXN")

# Canonical run order. R0 first so an interrupted run still leaves the baseline every other cell is
# read against; the 2x2 next; the controls last, since they are what makes the 2x2 readable rather
# than part of it.
CELL_ORDER = ("R0", *CELLS, "AF", "AV", "AN", *INCORRECT_VERDICT_CELLS)


def select_cells(requested: str, available: tuple[str, ...]) -> tuple[str, ...]:
    """Narrow a run to a comma-separated subset of the cells its inputs support.

    Raises rather than narrowing silently: asking for ``AF`` when ``--filler`` was omitted would run
    the arm with its control missing and leave every contrast comparing against nothing. Order comes
    from `CELL_ORDER`, not the caller's string, so the same subset always writes in one sequence.
    """
    if not requested.strip():
        return available
    names = [n.strip() for n in requested.split(",") if n.strip()]
    if unknown := [n for n in names if n not in CELL_ORDER]:
        raise SystemExit(f"unknown cell(s) {unknown}; expected some of {list(CELL_ORDER)}")
    if missing := [n for n in names if n not in available]:
        raise SystemExit(
            f"cell(s) {missing} were requested but this run's inputs do not support them "
            f"(available: {list(available)}); supply the matching --filler/--neutral/--warmup-* "
            "file rather than running the arm without its control"
        )
    return tuple(c for c in CELL_ORDER if c in names)


def check_pool_fingerprints(by_cell: dict[str, dict]) -> None:
    """Refuse a cell set whose same-pool members were built from different episodes.

    There are **two** legitimate pools: AX and AXN sit on faulty traces, so their hash differs from
    the ordinary cells' by design and an "all hashes agree" rule would fail a correct run. AX - AXN
    is a contrast *within* that pool, so those two must agree with each other. Cells with no hash
    (R0, and cells written before hashing) are skipped rather than treated as a third pool.
    """
    for group, cells in (("ordinary", [c for c in by_cell if c != "R0"
                                       and c not in INCORRECT_VERDICT_CELLS]),
                         ("incorrect-verdict", list(INCORRECT_VERDICT_CELLS))):
        prints = {c: by_cell[c]["episode_fingerprint"] for c in cells
                  if c in by_cell and by_cell[c].get("episode_fingerprint")}
        if len(set(prints.values())) > 1:
            raise SystemExit(
                f"{group} cells were built from different episode pools {prints}; regenerate the "
                "odd ones out rather than comparing across them"
            )


def warmup_content(warmup: WarmupEpisode, attribution: str) -> tuple[str, str, str]:
    """The episode's three pieces: audit request, labelled audit, labelled repair.

    One helper, so the byte identity the design depends on is structural rather than remembered.
    """
    if attribution not in LABELS:
        raise ValueError(f"unknown attribution {attribution!r}; expected {sorted(LABELS)}")
    label = LABELS[attribution]
    request = build_audit_messages(warmup.item, "R0", "F1")[1]["content"]
    return request, f"{label} {warmup.audit}", f"{label} {warmup.repair}"


def build_filler_messages(
    target: AuditItem,
    filler: FillerEpisode,
    family: str = "F1",
) -> list[dict]:
    """Assistant-placement context with no audit and no repair in it.

    Structurally identical to AS/AO down to the byte-identical target request, so the only
    difference is what the prior exchange was *about*.
    """
    base = build_audit_messages(target, "R0", family)
    system, target_request = base[0], base[1]["content"]
    return [
        system,
        {"role": "user", "content": filler.request},
        {"role": "assistant", "content": filler.response},
        {"role": "user", "content": f"{HANDOFF}\n\n{target_request}"},
    ]


def injected_candidates(pairs: list[dict], limit: int) -> list[AuditItem]:
    """Faulty traces to build incorrect-verdict episodes from, best-first.

    ``early`` faults come first for every trace before any ``late`` fault is taken: both arms of one
    trace differ only in which step was corrupted, so taking them together fills the pool with
    near-duplicates. The caller keeps only candidates whose audit actually reported an error, so
    filtering happens after generation.
    """
    ordered = [(arm, p) for arm in ("early", "late") for p in pairs]
    return [
        AuditItem(f"{p['id']}::{arm}", p["problem"], list(p[arm]["steps"]))
        for arm, p in ordered[:limit]
    ]


def natural_candidates(
    traces: list[dict],
    limit: int,
    exclude: frozenset[str] | set[str] = frozenset(),
) -> list[AuditItem]:
    """Faulty traces for the AX cell, taken from ProcessBench rather than from an injector.

    An injected fault has an author, and auditing a fault you wrote is self-attribution rather than
    verdict composition, which disqualified the injecting model from AX. Two guarantees:
    **round-robin across sources**, since the pool is lopsided and file order would confound episode
    variation with source; and **``exclude`` is honoured**, since the detection arm draws from this
    same split and a warmup item could otherwise collide with a target judged cold later.
    """
    queues: dict[str, list[AuditItem]] = {}
    for t in traces:
        # ProcessBench ids already carry the split ("gsm8k-212"), and every other pool in this
        # project stores them that way. Re-prefixing produced "gsm8k-gsm8k-212", which compares
        # fine against itself and silently fails to join against anything else.
        item_id = str(t["id"])
        if item_id in exclude:
            continue
        queues.setdefault(t["split"], []).append(
            AuditItem(item_id, t["problem"], list(t["steps"]))
        )

    out: list[AuditItem] = []
    while len(out) < limit and any(queues.values()):
        for q in queues.values():
            if q and len(out) < limit:
                out.append(q.pop(0))
    return out


def build_audit_only_messages(
    target: AuditItem,
    warmup: WarmupEpisode,
    family: str = "F1",
) -> list[dict]:
    """The AS cell with the repair turns removed, and nothing else changed.

    AF shows the effect is not context length, but it deletes the episode's *verdict* along with the
    repair -- and 88%/86% of the Qwen models' episodes report "correct", so those cells put a
    ``"verdict": "correct"`` assertion in front of a model about to emit that field. Keeping the
    audit and dropping only the repair makes AS - AV the repair's own contribution.
    """
    base = build_audit_messages(target, "R0", family)
    system, target_request = base[0], base[1]["content"]
    request, audit, _ = warmup_content(warmup, "self")
    return [
        system,
        {"role": "user", "content": request},
        {"role": "assistant", "content": audit},
        {"role": "user", "content": f"{HANDOFF}\n\n{target_request}"},
    ]


NEUTRAL_REQUEST = "Now restate, without changing it, what your audit concluded."


def neutral_map(blob: dict, label: str, pool: list[WarmupEpisode], cell: str) -> dict[str, str]:
    """Episode id -> its length-matched non-repair continuation, checked against the pool.

    The coverage check is the point: a continuation set missing some episodes would not fail on its
    own, and the cell would build on whatever subset was present, silently forming a contrast whose
    two sides use different episodes.
    """
    if blob["auditor"] != label:
        raise SystemExit(f"neutral set is {blob['auditor']!r}, endpoint is {label!r}")
    out = {n["item_id"]: n["neutral"] for n in blob["neutrals"]}
    missing = {e.item.item_id for e in pool} - out.keys()
    if missing:
        raise SystemExit(
            f"{len(missing)} of {len(pool)} episodes have no neutral continuation, e.g. "
            f"{sorted(missing)[:3]}; {cell} would silently fall back to a different pairing"
        )
    return out


def build_neutral_messages(
    target: AuditItem,
    warmup: WarmupEpisode,
    neutral: str,
    family: str = "F1",
) -> list[dict]:
    """The AS cell with the repair replaced by a non-repair continuation of matched length.

    AV varies the repair's presence and the episode's length at once, so `AS - AV` is not an
    identified repair contrast. AN keeps the audit and a continuation in the same turn, and makes it
    a restatement rather than a correction. That identifies ``AS - AN`` (the repair's contribution),
    ``AV - AN`` (whether *any* continuation matters) and ``AN - AF`` (audit plus inert turn vs
    non-audit). The caller owns the length matching; this only guarantees the structure.
    """
    base = build_audit_messages(target, "R0", family)
    system, target_request = base[0], base[1]["content"]
    request, audit, _ = warmup_content(warmup, "self")
    label = LABELS["self"]
    return [
        system,
        {"role": "user", "content": request},
        {"role": "assistant", "content": audit},
        {"role": "user", "content": NEUTRAL_REQUEST},
        {"role": "assistant", "content": f"{label} {neutral}"},
        {"role": "user", "content": f"{HANDOFF}\n\n{target_request}"},
    ]


def build_r4_messages(
    target: AuditItem,
    warmup: WarmupEpisode,
    cell: str,
    family: str = "F1",
) -> list[dict]:
    """Chat messages for one R4 cell.

    The final user turn is always the unmodified R0 audit request for ``target``: R4 adds
    history, it never rewords the present task.
    """
    if cell not in CELLS:
        raise ValueError(f"unknown cell {cell!r}; expected {CELLS}")

    base = build_audit_messages(target, "R0", family)
    system, target_request = base[0], base[1]["content"]
    request, audit, repair = warmup_content(warmup, _ATTRIBUTION[cell])

    if _PLACEMENT[cell] == "assistant":
        # Structurally the model's own prior work: it occupies the assistant turns.
        return [
            system,
            {"role": "user", "content": request},
            {"role": "assistant", "content": audit},
            {"role": "user", "content": REPAIR_REQUEST},
            {"role": "assistant", "content": repair},
            {"role": "user", "content": f"{HANDOFF}\n\n{target_request}"},
        ]

    # Off-policy: the identical episode is quoted inside a user turn, so no assistant turn
    # exists at all. This is the Khullar et al. placement manipulation.
    #
    # The episode and the target request go in SEPARATE user turns. Folding them into one
    # would make the final turn differ between placements -- assistant-placement cells end
    # with just handoff + target, user-placement cells would end with the whole transcript too
    # -- which is a structural difference on top of placement and would muddy the very
    # contrast the 2x2 exists to draw.
    transcript = "\n\n".join([request, audit, REPAIR_REQUEST, repair])
    return [
        system,
        {"role": "user", "content": transcript},
        {"role": "user", "content": f"{HANDOFF}\n\n{target_request}"},
    ]
